[package]
name = "server"
version = "0.0.1"
edition = "2021"
authors = ["Andrey Zheleznov <zheland.net@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.44"
async-std = "1.10.0"
clap = "3.0.0-beta.4"
env_logger = "0.9.0"

[dependencies.tracker]
path = "../tracker"
